name       : perl-parallel-forkmanager
version    : 2.02
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/Y/YA/YANICK/Parallel-ForkManager-2.02.tar.gz : c1b2970a8bb666c3de7caac4a8f4dbcc043ab819bbc337692ec7bf27adae4404
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Parallel::ForkManager - A simple parallel processing fork manager
description: |
    Parallel::ForkManager - A simple parallel processing fork manager
builddeps  :
    - perl-moo
rundeps    :
    - perl-moo
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
